#!/bin/sh
if [ -x "/var/jb/usr/bin/uicache" ]; then
    /var/jb/usr/bin/uicache -p /var/jb/Applications/DeviceStats.app
elif [ -x "/usr/bin/uicache" ]; then
    /usr/bin/uicache -p /Applications/DeviceStats.app 2>/dev/null || /usr/bin/uicache -a
fi
exit 0